version: "3"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "180:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      PIHOLE_DNS_: 10.10.10.3
      WEBPASSWORD: ''
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: unless-stopped
    networks:
      pibound:
        ipv4_address: 10.10.10.2
    depends_on:
     - unbound
  
  unbound:
    container_name: unbound
    hostname: unbound
    build:
      context: .
      dockerfile: dockerfile-unbound
    volumes:
      - './unbound.conf:/etc/unbound/unbound.conf.d/unbound.conf'
    restart: unless-stopped
    networks:
      pibound:
        ipv4_address: 10.10.10.3

networks:
  pibound:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/24
